#!/usr/bin/env python3
"""On blocked label: fetch issue context; call Claude for resolution suggestions; post comment."""

import os
import sys
from pathlib import Path

import requests
import anthropic

ROOT = Path(__file__).parent.parent.parent
MODEL = "claude-sonnet-4-6"


def gh_headers(token: str) -> dict:
    return {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}


def get_issue(token: str, repo: str, issue_number: int) -> dict:
    resp = requests.get(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}",
        headers=gh_headers(token),
    )
    resp.raise_for_status()
    return resp.json()


def get_recent_closed_issues(token: str, repo: str, limit: int = 50) -> list:
    items = []
    page = 1
    while len(items) < limit:
        resp = requests.get(
            f"https://api.github.com/repos/{repo}/issues",
            headers=gh_headers(token),
            params={"state": "closed", "per_page": min(100, limit - len(items)), "page": page},
        )
        resp.raise_for_status()
        data = resp.json()
        if not data:
            break
        items.extend(data)
        if len(data) < 100:
            break
        page += 1
    return [i for i in items if "pull_request" not in i][:limit]


def post_comment(token: str, repo: str, issue_number: int, body: str) -> None:
    resp = requests.post(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments",
        headers=gh_headers(token),
        json={"body": body},
    )
    resp.raise_for_status()


def main() -> None:
    if len(sys.argv) < 3:
        sys.exit("Usage: blocker-resolver.py <owner/repo> <issue-number>")

    repo = sys.argv[1]
    issue_number = int(sys.argv[2])

    gh_token = os.environ.get("OCTO_PAT") or os.environ.get("GITHUB_TOKEN")
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY")
    if not gh_token:
        sys.exit("Error: OCTO_PAT or GITHUB_TOKEN required.")
    if not anthropic_key:
        sys.exit("Error: ANTHROPIC_API_KEY required.")

    print(f"Fetching issue {repo}#{issue_number}...")
    issue = get_issue(gh_token, repo, issue_number)

    print("Fetching recent closed issues for context...")
    closed_issues = get_recent_closed_issues(gh_token, repo)

    closed_summary = "\n".join(
        f"- #{i['number']}: {i['title']}" for i in closed_issues[:30]
    )

    client = anthropic.Anthropic(api_key=anthropic_key)

    message = client.messages.create(
        model=MODEL,
        max_tokens=500,
        messages=[
            {
                "role": "user",
                "content": (
                    f"A GitHub issue has been labeled 'blocked'. Help resolve it.\n\n"
                    f"Blocked issue:\nTitle: {issue['title']}\n"
                    f"Description: {(issue.get('body') or '')[:1000]}\n"
                    f"Assignee: {issue['assignee']['login'] if issue.get('assignee') else 'unassigned'}\n\n"
                    f"Recent closed issues in this repo (for context):\n{closed_summary}\n\n"
                    f"Provide:\n"
                    f"1. 2-3 concrete resolution suggestions specific to this blocker\n"
                    f"2. A recommended owner or team to contact\n"
                    f"3. Reference to a similar resolved issue from the list above, if one exists\n\n"
                    f"Format as a brief GitHub comment (markdown). Be specific and actionable."
                ),
            }
        ],
    )

    suggestions = message.content[0].text.strip()
    comment = (
        f":robot: **Blocker Resolver** — AI-generated resolution suggestions\n\n"
        f"{suggestions}\n\n"
        f"---\n"
        f"*Generated by Program Hub. Review before acting on these suggestions.*"
    )

    print("Posting resolution suggestions...")
    post_comment(gh_token, repo, issue_number, comment)
    print("Done.")


if __name__ == "__main__":
    main()
