#!/usr/bin/env python3
"""Identify coupled issue pairs across initiatives; write DEPENDENCY-MAP.md. Uses prompt caching."""

import json
import os
import sys
from datetime import datetime, timezone
from itertools import combinations
from pathlib import Path

import yaml
import requests
import anthropic

ROOT = Path(__file__).parent.parent.parent
MODEL = "claude-sonnet-4-6"

SYSTEM_PROMPT = """You are a program manager analysing GitHub issues across multiple engineering initiatives.
Your task is to identify pairs of issues from DIFFERENT initiatives that are likely coupled — meaning
one cannot be completed without the other, or one's delay would directly cause the other to slip.

Coupling signals to look for:
- Shared API or interface contracts
- One issue explicitly references another team's work
- Same data model or schema changes needed by both
- Shared infrastructure or service dependency
- Authentication, authorisation, or identity flows touched by both
- Explicit "waiting on X team" language

Return a JSON array of coupled pairs:
[{"initiative_a": "...", "issue_a": "#N title", "initiative_b": "...", "issue_b": "#N title",
  "reason": "one sentence explaining the coupling", "severity": "high|medium|low"}, ...]

Return [] if no coupling is found. Return JSON only — no markdown, no explanation."""


def gh_search(token: str, query: str) -> list:
    items = []
    page = 1
    while len(items) < 200:
        resp = requests.get(
            "https://api.github.com/search/issues",
            headers={"Authorization": f"token {token}", "Accept": "application/vnd.github+json"},
            params={"q": query, "per_page": 100, "page": page},
        )
        resp.raise_for_status()
        data = resp.json()
        items.extend(data.get("items", []))
        if len(items) >= data.get("total_count", 0) or not data.get("items"):
            break
        page += 1
    return items


def main() -> None:
    gh_token = os.environ.get("OCTO_PAT") or os.environ.get("GITHUB_TOKEN")
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY")
    if not gh_token:
        sys.exit("Error: OCTO_PAT or GITHUB_TOKEN required.")
    if not anthropic_key:
        sys.exit("Error: ANTHROPIC_API_KEY required.")

    client = anthropic.Anthropic(api_key=anthropic_key)

    initiatives_dir = ROOT / "initiatives"
    all_configs = []
    for config_path in sorted(initiatives_dir.glob("*/config.yml")):
        cfg = yaml.safe_load(config_path.read_text())
        all_configs.append(cfg)

    if len(all_configs) < 2:
        print("Need at least 2 initiatives to find dependencies.")
        return

    # Collect open issues per initiative
    initiative_issues = {}
    for cfg in all_configs:
        repo = cfg["source_repo"]
        name = cfg["name"]
        print(f"Fetching open issues for {repo}...")
        issues = gh_search(gh_token, f"repo:{repo} is:issue is:open")
        summary = "\n".join(f"  #{i['number']}: {i['title']}" for i in issues[:50])
        initiative_issues[name] = summary

    # For each pair of initiatives, call Claude to find coupling
    all_pairs = []
    for (name_a, issues_a), (name_b, issues_b) in combinations(initiative_issues.items(), 2):
        print(f"Checking coupling: {name_a} ↔ {name_b}...")

        user_content = (
            f"Initiative A: {name_a}\nOpen issues:\n{issues_a}\n\n"
            f"Initiative B: {name_b}\nOpen issues:\n{issues_b}\n\n"
            f"Identify coupled issue pairs between these two initiatives."
        )

        message = client.messages.create(
            model=MODEL,
            max_tokens=800,
            system=[
                {
                    "type": "text",
                    "text": SYSTEM_PROMPT,
                    "cache_control": {"type": "ephemeral"},
                }
            ],
            messages=[{"role": "user", "content": user_content}],
        )

        try:
            pairs = json.loads(message.content[0].text.strip())
            all_pairs.extend(pairs)
        except json.JSONDecodeError:
            print(f"  Warning: could not parse JSON response for {name_a} ↔ {name_b}")

    as_of = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        "<!-- AUTO-REGENERATED by ai/feature-14-dependency-graph/dependency-graph.py -->",
        "",
        "# Dependency Map",
        "",
        f"**As of:** {as_of}",
        "",
        "Cross-initiative issue pairs identified as likely coupled by AI analysis.",
        "",
        "| Severity | Initiative A | Issue A | Initiative B | Issue B | Reason |",
        "|----------|-------------|---------|-------------|---------|--------|",
    ]

    severity_order = {"high": 0, "medium": 1, "low": 2}
    all_pairs.sort(key=lambda p: severity_order.get(p.get("severity", "low"), 2))

    if all_pairs:
        for pair in all_pairs:
            sev = pair.get("severity", "medium").capitalize()
            ia = pair.get("initiative_a", "")
            issa = pair.get("issue_a", "").replace("|", "\\|")
            ib = pair.get("initiative_b", "")
            issb = pair.get("issue_b", "").replace("|", "\\|")
            reason = pair.get("reason", "").replace("|", "\\|")
            lines.append(f"| {sev} | {ia} | {issa} | {ib} | {issb} | {reason} |")
    else:
        lines.append("| — | No coupled issue pairs identified | — | — | — | — |")

    lines += [
        "",
        "---",
        "*Table regenerated every Friday. AI may miss couplings or flag false positives — review with engineering leads.*",
    ]

    dep_map_path = ROOT / "program" / "DEPENDENCY-MAP.md"
    dep_map_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {dep_map_path}")


if __name__ == "__main__":
    main()
