#!/usr/bin/env python3
"""Append a single risk row to RISK-REGISTER.md without overwriting existing rows."""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml
import requests

ROOT = Path(__file__).parent.parent


def gh_headers(token: str) -> dict:
    return {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}


def days_open(created_at_str: str) -> int:
    created = datetime.fromisoformat(created_at_str.replace("Z", "+00:00"))
    return (datetime.now(timezone.utc) - created).days


def main() -> None:
    if len(sys.argv) < 4:
        sys.exit("Usage: append-risk-register.py <initiative-slug> <issue-number> <label>")

    slug = sys.argv[1]
    issue_number = int(sys.argv[2])
    label = sys.argv[3]

    token = os.environ.get("OCTO_PAT") or os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.exit("Error: OCTO_PAT or GITHUB_TOKEN env var required.")

    config_path = ROOT / "initiatives" / slug / "config.yml"
    config = yaml.safe_load(config_path.read_text())
    repo = config["source_repo"]

    # Fetch issue details
    resp = requests.get(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}",
        headers=gh_headers(token),
    )
    resp.raise_for_status()
    issue = resp.json()

    issue_url = issue["html_url"]
    issue_ref = f"{repo}#{issue_number}"

    risk_path = ROOT / "initiatives" / slug / "RISK-REGISTER.md"

    # Check for duplicate
    if risk_path.exists():
        existing = risk_path.read_text()
        if issue_url in existing or issue_ref in existing:
            print(f"Risk for {issue_ref} already in register — skipping.")
            return

    # Determine next Risk ID
    next_id = 1
    if risk_path.exists():
        import re
        ids = re.findall(r"\| R(\d+) \|", existing)
        if ids:
            next_id = max(int(i) for i in ids) + 1

    risk_id = f"R{next_id:03d}"
    title = issue["title"].replace("|", "\\|")
    d_open = days_open(issue["created_at"])
    assignee = f"@{issue['assignee']['login']}" if issue.get("assignee") else "unassigned"
    flagged = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    new_row = f"| {risk_id} | {title} | {label} | {d_open} | {assignee} | {flagged} | {issue_ref} |"

    if risk_path.exists():
        text = risk_path.read_text()
        # Find the last data row in the table and append after it
        lines = text.splitlines()
        # Find the table separator line and insert new row before the blank line after the table
        insert_idx = None
        in_table = False
        for i, line in enumerate(lines):
            if line.startswith("|------"):
                in_table = True
            elif in_table and line.startswith("|"):
                insert_idx = i
            elif in_table and not line.startswith("|"):
                break

        if insert_idx is not None:
            lines.insert(insert_idx + 1, new_row)
            risk_path.write_text("\n".join(lines) + "\n")
        else:
            # Fallback: append before the trailing separator
            risk_path.write_text(text.rstrip() + "\n" + new_row + "\n")
    else:
        # Create new register
        header_lines = [
            "<!-- AUTO-REGENERATED by scripts/update-risk-register.py — do not edit data rows manually -->",
            "",
            f"# Risk Register — {config['name']}",
            "",
            "| Risk ID | Title | Label | Days Open | Assignee | Date Flagged | Issue |",
            "|---------|-------|-------|-----------|----------|--------------|-------|",
            new_row,
            "",
            "---",
            "*Rows are appended automatically when `blocked` or `dependency` labels are applied.*",
        ]
        risk_path.write_text("\n".join(header_lines) + "\n")

    print(f"Appended {risk_id} to {risk_path}")


if __name__ == "__main__":
    main()
