#!/usr/bin/env python3
"""Read issues filtered by pod label; write STANDUP.md per pod."""

import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import yaml
import requests

ROOT = Path(__file__).parent.parent


def gh_headers(token: str) -> dict:
    return {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}


def gh_search(token: str, query: str) -> list:
    items = []
    page = 1
    while True:
        resp = requests.get(
            "https://api.github.com/search/issues",
            headers=gh_headers(token),
            params={"q": query, "per_page": 100, "page": page},
        )
        resp.raise_for_status()
        data = resp.json()
        items.extend(data.get("items", []))
        if len(items) >= data.get("total_count", 0) or not data.get("items"):
            break
        page += 1
    return items


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit("Usage: update-pod-standups.py <initiative-slug>")

    slug = sys.argv[1]
    token = os.environ.get("OCTO_PAT") or os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.exit("Error: OCTO_PAT or GITHUB_TOKEN env var required.")

    config_path = ROOT / "initiatives" / slug / "config.yml"
    config = yaml.safe_load(config_path.read_text())
    repo = config["source_repo"]
    blocked_label = config["labels"]["blocked"]

    since_24h = (datetime.now(timezone.utc) - timedelta(hours=24)).strftime("%Y-%m-%dT%H:%M:%SZ")
    as_of = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    for pod in config.get("pods", []):
        pod_label = pod["label"]
        pod_name = pod["name"]
        pod_slug = pod["slug"]

        print(f"Fetching issues for pod '{pod_name}' (label: {pod_label})...")

        # Done: closed in last 24h with pod label
        done_items = gh_search(
            token,
            f"repo:{repo} is:issue is:closed label:{pod_label} closed:>={since_24h[:10]}"
        )

        # In Progress: open with pod label, not blocked
        in_progress_items = gh_search(
            token,
            f"repo:{repo} is:issue is:open label:{pod_label} -label:{blocked_label}"
        )

        # Blocked: open with pod label AND blocked label
        blocked_items = gh_search(
            token,
            f"repo:{repo} is:issue is:open label:{pod_label} label:{blocked_label}"
        )

        lines = [
            "<!-- AUTO-REGENERATED by scripts/update-pod-standups.py — do not edit manually -->",
            "",
            f"# Standup — {pod_name}",
            "",
            f"**Initiative:** {config['name']} &nbsp;|&nbsp; **Pod:** {pod_name} &nbsp;|&nbsp; **As of:** {as_of}",
            "",
            "## Done (closed in last 24h)",
            "",
        ]

        if done_items:
            lines += ["| # | Title |", "|---|-------|"]
            for i, issue in enumerate(done_items, 1):
                title = issue["title"].replace("|", "\\|")
                lines.append(f"| {i} | {title} |")
        else:
            lines.append("None.")

        lines += ["", "## In Progress", ""]
        if in_progress_items:
            lines += ["| # | Title | Assignee |", "|---|-------|----------|"]
            for i, issue in enumerate(in_progress_items, 1):
                title = issue["title"].replace("|", "\\|")
                assignee = f"@{issue['assignee']['login']}" if issue.get("assignee") else "unassigned"
                lines.append(f"| {i} | {title} | {assignee} |")
        else:
            lines.append("None.")

        lines += ["", "## Blocked", ""]
        if blocked_items:
            lines += ["| # | Title | Assignee |", "|---|-------|----------|"]
            for i, issue in enumerate(blocked_items, 1):
                title = issue["title"].replace("|", "\\|")
                assignee = f"@{issue['assignee']['login']}" if issue.get("assignee") else "unassigned"
                lines.append(f"| {i} | {title} | {assignee} |")
        else:
            lines.append("None.")

        pod_dir = ROOT / "initiatives" / slug / "pods" / pod_slug
        pod_dir.mkdir(parents=True, exist_ok=True)
        standup_path = pod_dir / "STANDUP.md"
        standup_path.write_text("\n".join(lines) + "\n")
        print(f"Wrote {standup_path}")


if __name__ == "__main__":
    main()
