#!/usr/bin/env python3
"""Read all initiative configs; write cross-initiative PROGRAM-RISKS.md sorted by age."""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml
import requests

ROOT = Path(__file__).parent.parent


def gh_headers(token: str) -> dict:
    return {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}


def gh_search(token: str, query: str) -> list:
    items = []
    page = 1
    while True:
        resp = requests.get(
            "https://api.github.com/search/issues",
            headers=gh_headers(token),
            params={"q": query, "per_page": 100, "page": page},
        )
        resp.raise_for_status()
        data = resp.json()
        items.extend(data.get("items", []))
        if len(items) >= data.get("total_count", 0) or not data.get("items"):
            break
        page += 1
    return items


def days_open(created_at_str: str) -> int:
    created = datetime.fromisoformat(created_at_str.replace("Z", "+00:00"))
    return (datetime.now(timezone.utc) - created).days


def main() -> None:
    token = os.environ.get("OCTO_PAT") or os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.exit("Error: OCTO_PAT or GITHUB_TOKEN env var required.")

    initiatives_dir = ROOT / "initiatives"
    all_risks = []

    for config_path in sorted(initiatives_dir.glob("*/config.yml")):
        cfg = yaml.safe_load(config_path.read_text())
        repo = cfg["source_repo"]
        blocked_label = cfg["labels"]["blocked"]
        dep_label = cfg["labels"]["dependency"]
        initiative_name = cfg["name"]

        print(f"Querying {repo}...")

        seen = set()
        for label in [blocked_label, dep_label]:
            items = gh_search(token, f"repo:{repo} is:issue is:open label:{label}")
            for issue in items:
                if issue["number"] not in seen:
                    seen.add(issue["number"])
                    all_risks.append({
                        "initiative": initiative_name,
                        "issue": issue,
                        "label": label,
                        "days": days_open(issue["created_at"]),
                    })

    # Sort by age descending
    all_risks.sort(key=lambda x: x["days"], reverse=True)

    as_of = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        "<!-- AUTO-REGENERATED by scripts/update-program-risks.py — do not edit data rows manually -->",
        "",
        "# Program Risks",
        "",
        f"**As of:** {as_of}",
        "",
        "## Cross-Initiative Risk Table",
        "",
        "| Initiative | Risk ID | Title | Label | Days Open | Assignee | Date Flagged | Issue |",
        "|------------|---------|-------|-------|-----------|----------|--------------|-------|",
    ]

    if all_risks:
        for i, r in enumerate(all_risks, 1):
            issue = r["issue"]
            risk_id = f"R{i:03d}"
            title = issue["title"].replace("|", "\\|")
            assignee = f"@{issue['assignee']['login']}" if issue.get("assignee") else "unassigned"
            flagged = issue["created_at"][:10]
            repo = issue["repository_url"].split("/repos/")[1] if "repository_url" in issue else "?"
            issue_ref = f"{repo}#{issue['number']}"
            lines.append(
                f"| {r['initiative']} | {risk_id} | {title} | {r['label']} | "
                f"{r['days']} | {assignee} | {flagged} | {issue_ref} |"
            )
    else:
        lines.append("| — | — | No risks flagged | — | — | — | — | — |")

    lines += [
        "",
        "---",
        "*Rows are sorted by age (oldest first). Table is regenerated every Monday, Wednesday, and Friday.*",
    ]

    risks_path = ROOT / "program" / "PROGRAM-RISKS.md"
    risks_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {risks_path}")


if __name__ == "__main__":
    main()
