#!/usr/bin/env python3
"""Read blocked + dependency issues from source repo; write RISK-REGISTER.md."""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml
import requests

ROOT = Path(__file__).parent.parent


def gh_headers(token: str) -> dict:
    return {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}


def gh_search(token: str, query: str) -> list:
    items = []
    page = 1
    while True:
        resp = requests.get(
            "https://api.github.com/search/issues",
            headers=gh_headers(token),
            params={"q": query, "per_page": 100, "page": page},
        )
        resp.raise_for_status()
        data = resp.json()
        items.extend(data.get("items", []))
        if len(items) >= data.get("total_count", 0) or not data.get("items"):
            break
        page += 1
    return items


def days_open(created_at_str: str) -> int:
    created = datetime.fromisoformat(created_at_str.replace("Z", "+00:00"))
    return (datetime.now(timezone.utc) - created).days


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit("Usage: update-risk-register.py <initiative-slug>")

    slug = sys.argv[1]
    token = os.environ.get("OCTO_PAT") or os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.exit("Error: OCTO_PAT or GITHUB_TOKEN env var required.")

    config_path = ROOT / "initiatives" / slug / "config.yml"
    config = yaml.safe_load(config_path.read_text())
    repo = config["source_repo"]
    blocked_label = config["labels"]["blocked"]
    dependency_label = config["labels"]["dependency"]

    print(f"Fetching blocked issues for {repo}...")
    blocked_items = gh_search(token, f"repo:{repo} is:issue is:open label:{blocked_label}")
    print(f"Fetching dependency issues for {repo}...")
    dep_items = gh_search(token, f"repo:{repo} is:issue is:open label:{dependency_label}")

    # Merge, deduplicate by issue number
    seen = set()
    all_risks = []
    for item in blocked_items:
        if item["number"] not in seen:
            seen.add(item["number"])
            all_risks.append((item, blocked_label))
    for item in dep_items:
        if item["number"] not in seen:
            seen.add(item["number"])
            all_risks.append((item, dependency_label))

    # Sort by days open descending
    all_risks.sort(key=lambda x: days_open(x[0]["created_at"]), reverse=True)

    lines = [
        "<!-- AUTO-REGENERATED by scripts/update-risk-register.py — do not edit data rows manually -->",
        "",
        f"# Risk Register — {config['name']}",
        "",
        "| Risk ID | Title | Label | Days Open | Assignee | Date Flagged | Issue |",
        "|---------|-------|-------|-----------|----------|--------------|-------|",
    ]

    if all_risks:
        for i, (issue, label) in enumerate(all_risks, 1):
            risk_id = f"R{i:03d}"
            title = issue["title"].replace("|", "\\|")
            d_open = days_open(issue["created_at"])
            assignee = f"@{issue['assignee']['login']}" if issue.get("assignee") else "unassigned"
            flagged = issue["created_at"][:10]
            issue_ref = f"{repo}#{issue['number']}"
            lines.append(f"| {risk_id} | {title} | {label} | {d_open} | {assignee} | {flagged} | {issue_ref} |")
    else:
        lines.append("| — | No risks flagged | — | — | — | — | — |")

    lines += [
        "",
        "---",
        "*Rows are appended automatically when `blocked` or `dependency` labels are applied to issues in the source repository.*",
    ]

    risk_path = ROOT / "initiatives" / slug / "RISK-REGISTER.md"
    risk_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {risk_path}")


if __name__ == "__main__":
    main()
