#!/usr/bin/env python3
"""Read closed/blocked issues from source repo; write STATUS.md."""

import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import yaml
import requests

ROOT = Path(__file__).parent.parent


def gh_headers(token: str) -> dict:
    return {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}


def gh_search(token: str, query: str) -> list:
    items = []
    page = 1
    while True:
        resp = requests.get(
            "https://api.github.com/search/issues",
            headers=gh_headers(token),
            params={"q": query, "per_page": 100, "page": page},
        )
        resp.raise_for_status()
        data = resp.json()
        items.extend(data.get("items", []))
        if len(items) >= data.get("total_count", 0) or not data.get("items"):
            break
        page += 1
    return items


def week_number(week_start_str: str) -> int:
    week_start = datetime.fromisoformat(week_start_str).date()
    today = datetime.now(timezone.utc).date()
    delta = (today - week_start).days
    return max(1, delta // 7 + 1)


def health_signal(blocked_count: int) -> str:
    if blocked_count == 0:
        return "Green"
    elif blocked_count <= 2:
        return "Amber"
    else:
        return "Red"


def health_emoji(signal: str) -> str:
    return {"Green": "🟢", "Amber": "🟡", "Red": "🔴"}.get(signal, "⚪")


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit("Usage: update-status.py <initiative-slug>")

    slug = sys.argv[1]
    token = os.environ.get("OCTO_PAT") or os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.exit("Error: OCTO_PAT or GITHUB_TOKEN env var required.")

    config_path = ROOT / "initiatives" / slug / "config.yml"
    if not config_path.exists():
        sys.exit(f"Error: config not found at {config_path}")

    config = yaml.safe_load(config_path.read_text())
    repo = config["source_repo"]
    blocked_label = config["labels"]["blocked"]
    dependency_label = config["labels"]["dependency"]
    week_start = config["week_start"]
    duration_weeks = config["duration_weeks"]

    since = (datetime.now(timezone.utc) - timedelta(days=7)).strftime("%Y-%m-%dT%H:%M:%SZ")

    print(f"Fetching closed issues for {repo} (last 7 days)...")
    closed_items = gh_search(token, f"repo:{repo} is:issue is:closed closed:>={since[:10]}")

    print(f"Fetching blocked issues for {repo}...")
    blocked_items = gh_search(token, f"repo:{repo} is:issue is:open label:{blocked_label}")

    print(f"Fetching dependency issues for {repo}...")
    dependency_items = gh_search(token, f"repo:{repo} is:issue is:open label:{dependency_label}")

    current_week = week_number(str(week_start))
    signal = health_signal(len(blocked_items))
    as_of = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Build STATUS.md — preserve PM narrative if file exists
    status_path = ROOT / "initiatives" / slug / "STATUS.md"
    pm_narrative = "*No narrative added yet.*"
    if status_path.exists():
        text = status_path.read_text()
        # Extract PM narrative block
        marker = "<!-- PM: add narrative context here"
        if marker in text:
            parts = text.split(marker)
            if len(parts) > 1:
                after = parts[1]
                end = after.find("-->")
                if end != -1:
                    narrative_block = after[end + 3:].strip()
                    if narrative_block:
                        pm_narrative = narrative_block

    lines = [
        "<!-- AUTO-REGENERATED by scripts/update-status.py — do not edit data rows manually -->",
        "<!-- PM narrative placeholder is preserved across regenerations -->",
        "",
        f"# Status — {config['name']}",
        "",
        f"**Week:** {current_week} of {duration_weeks} &nbsp;|&nbsp; "
        f"**Health:** {health_emoji(signal)} {signal} &nbsp;|&nbsp; **As of:** {as_of}",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Sprint week | {current_week} / {duration_weeks} |",
        f"| Issues closed (last 7 days) | {len(closed_items)} |",
        f"| Open blockers | {len(blocked_items)} |",
        f"| Open dependencies | {len(dependency_items)} |",
        f"| Health signal | {signal} |",
        "",
        "## Closed This Week",
        "",
    ]

    if closed_items:
        lines += ["| # | Title | Closed at |", "|---|-------|-----------|"]
        for i, issue in enumerate(closed_items[:20], 1):
            closed_at = (issue.get("closed_at") or "")[:10]
            title = issue["title"].replace("|", "\\|")
            lines.append(f"| {i} | {title} | {closed_at} |")
    else:
        lines.append("None.")

    lines += ["", "## Blockers", ""]
    if blocked_items:
        lines += ["| # | Title | Issue | Assignee |", "|---|-------|-------|----------|"]
        for i, issue in enumerate(blocked_items, 1):
            title = issue["title"].replace("|", "\\|")
            assignee = issue["assignee"]["login"] if issue.get("assignee") else "unassigned"
            lines.append(f"| {i} | {title} | #{issue['number']} | @{assignee} |")
    else:
        lines.append("None.")

    lines += ["", "## Dependencies", ""]
    if dependency_items:
        lines += ["| # | Title | Issue | Assignee |", "|---|-------|-------|----------|"]
        for i, issue in enumerate(dependency_items, 1):
            title = issue["title"].replace("|", "\\|")
            assignee = issue["assignee"]["login"] if issue.get("assignee") else "unassigned"
            lines.append(f"| {i} | {title} | #{issue['number']} | @{assignee} |")
    else:
        lines.append("None.")

    lines += [
        "",
        "---",
        "<!-- PM: add narrative context here — this block is preserved on regeneration -->",
        pm_narrative,
    ]

    status_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {status_path}")


if __name__ == "__main__":
    main()
