#!/usr/bin/env python3
"""Read all initiative configs; write PROGRAM-DASHBOARD.md."""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml
import requests

ROOT = Path(__file__).parent.parent


def gh_headers(token: str) -> dict:
    return {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}


def gh_search_count(token: str, query: str) -> int:
    resp = requests.get(
        "https://api.github.com/search/issues",
        headers=gh_headers(token),
        params={"q": query, "per_page": 1},
    )
    resp.raise_for_status()
    return resp.json().get("total_count", 0)


def week_number(week_start) -> tuple:
    if isinstance(week_start, str):
        week_start = datetime.fromisoformat(week_start).date()
    today = datetime.now(timezone.utc).date()
    delta = (today - week_start).days
    return max(1, delta // 7 + 1)


def health_signal(blocked_count: int) -> str:
    if blocked_count == 0:
        return "🟢 Green"
    elif blocked_count <= 2:
        return "🟡 Amber"
    else:
        return "🔴 Red"


def main() -> None:
    token = os.environ.get("OCTO_PAT") or os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.exit("Error: OCTO_PAT or GITHUB_TOKEN env var required.")

    initiatives_dir = ROOT / "initiatives"
    configs = []
    for config_path in sorted(initiatives_dir.glob("*/config.yml")):
        cfg = yaml.safe_load(config_path.read_text())
        configs.append(cfg)

    as_of = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    rows = []
    attention = []

    for cfg in configs:
        repo = cfg["source_repo"]
        blocked_label = cfg["labels"]["blocked"]
        slug = cfg["slug"]

        print(f"Querying {repo}...")
        open_count = gh_search_count(token, f"repo:{repo} is:issue is:open")
        blocked_count = gh_search_count(token, f"repo:{repo} is:issue is:open label:{blocked_label}")

        week_start = cfg.get("week_start", "")
        duration = cfg.get("duration_weeks", 8)
        current_week = week_number(str(week_start)) if week_start else "?"
        health = health_signal(blocked_count)
        showcase = cfg.get("showcase_date", "TBD")

        rows.append({
            "name": cfg["name"],
            "owner": cfg["owner"],
            "week": f"{current_week} / {duration}",
            "open": open_count,
            "blocked": blocked_count,
            "health": health,
            "showcase": showcase,
            "slug": slug,
        })

        if blocked_count > 0:
            attention.append(f"- **{cfg['name']}**: {blocked_count} open blocker(s) — see [risk register](../initiatives/{slug}/RISK-REGISTER.md)")

    # Preserve PM narrative
    dash_path = ROOT / "program" / "PROGRAM-DASHBOARD.md"
    pm_narrative = "*No narrative added yet.*"
    if dash_path.exists():
        text = dash_path.read_text()
        marker = "<!-- PM: add cross-initiative narrative here"
        if marker in text:
            parts = text.split(marker)
            if len(parts) > 1:
                after = parts[1]
                end = after.find("-->")
                if end != -1:
                    narrative_block = after[end + 3:].strip()
                    if narrative_block:
                        pm_narrative = narrative_block

    lines = [
        "<!-- AUTO-REGENERATED by scripts/update-program-dashboard.py — do not edit data rows manually -->",
        "",
        "# Program Dashboard",
        "",
        f"**As of:** {as_of}",
        "",
        "## Initiative Health",
        "",
        "| Initiative | Owner | Week | Open Issues | Blockers | Health | Showcase Date |",
        "|------------|-------|------|-------------|----------|--------|---------------|",
    ]

    for row in rows:
        lines.append(
            f"| {row['name']} | {row['owner']} | {row['week']} | "
            f"{row['open']} | {row['blocked']} | {row['health']} | {row['showcase']} |"
        )

    lines += ["", "## PM Attention Required", ""]
    if attention:
        lines.extend(attention)
    else:
        lines.append("None at this time.")

    lines += [
        "",
        "---",
        "<!-- PM: add cross-initiative narrative here — preserved on regeneration -->",
        pm_narrative,
    ]

    dash_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {dash_path}")


if __name__ == "__main__":
    main()
