#!/usr/bin/env python3
"""Read all initiative configs; prepend weekly section to PROGRAM-CHANGELOG.md."""

import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import yaml
import requests

ROOT = Path(__file__).parent.parent


def gh_headers(token: str) -> dict:
    return {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}


def gh_search(token: str, query: str) -> list:
    items = []
    page = 1
    while True:
        resp = requests.get(
            "https://api.github.com/search/issues",
            headers=gh_headers(token),
            params={"q": query, "per_page": 100, "page": page},
        )
        resp.raise_for_status()
        data = resp.json()
        items.extend(data.get("items", []))
        if len(items) >= data.get("total_count", 0) or not data.get("items"):
            break
        page += 1
    return items


def week_start_monday() -> str:
    today = datetime.now(timezone.utc).date()
    monday = today - timedelta(days=today.weekday())
    return str(monday)


def main() -> None:
    token = os.environ.get("OCTO_PAT") or os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.exit("Error: OCTO_PAT or GITHUB_TOKEN env var required.")

    initiatives_dir = ROOT / "initiatives"
    configs = []
    for config_path in sorted(initiatives_dir.glob("*/config.yml")):
        cfg = yaml.safe_load(config_path.read_text())
        configs.append(cfg)

    since = (datetime.now(timezone.utc) - timedelta(days=7)).strftime("%Y-%m-%dT%H:%M:%SZ")
    week_label = week_start_monday()

    shipped_rows = []
    blockers_rows = []

    for cfg in configs:
        repo = cfg["source_repo"]
        blocked_label = cfg["labels"]["blocked"]
        name = cfg["name"]

        print(f"Querying {repo}...")
        closed = gh_search(token, f"repo:{repo} is:issue is:closed closed:>={since[:10]}")
        for issue in closed[:10]:
            title = issue["title"].replace("|", "\\|")
            closed_at = issue.get("closed_at", "")[:10]
            shipped_rows.append(f"| {name} | {title} | {closed_at} |")

        blocked = gh_search(token, f"repo:{repo} is:issue is:open label:{blocked_label}")
        for issue in blocked:
            title = issue["title"].replace("|", "\\|")
            assignee = f"@{issue['assignee']['login']}" if issue.get("assignee") else "unassigned"
            blockers_rows.append(f"| {name} | {title} | {assignee} |")

    new_section_lines = [
        f"## Week of {week_label}",
        "",
        "<!-- PM: add narrative for this week here -->",
        "*No narrative added yet.*",
        "",
        "### Shipped",
        "",
    ]

    if shipped_rows:
        new_section_lines += [
            "| Initiative | Item | Closed at |",
            "|------------|------|-----------|",
        ]
        new_section_lines.extend(shipped_rows)
    else:
        new_section_lines.append("Nothing shipped this week.")

    new_section_lines += ["", "### Open Blockers", ""]
    if blockers_rows:
        new_section_lines += [
            "| Initiative | Title | Assignee |",
            "|------------|-------|----------|",
        ]
        new_section_lines.extend(blockers_rows)
    else:
        new_section_lines.append("None.")

    new_section_lines.append("")
    new_section_lines.append("---")
    new_section_lines.append("")

    new_section = "\n".join(new_section_lines)

    changelog_path = ROOT / "program" / "PROGRAM-CHANGELOG.md"

    if changelog_path.exists():
        existing = changelog_path.read_text()
        # Check if this week's section already exists
        if f"## Week of {week_label}" in existing:
            print(f"Week of {week_label} already in changelog — skipping.")
            return
        # Prepend after the header (first line starting with "---")
        header_end = existing.find("\n---\n")
        if header_end != -1:
            updated = existing[: header_end + 5] + "\n" + new_section + existing[header_end + 5:]
        else:
            updated = existing + "\n" + new_section
        changelog_path.write_text(updated)
    else:
        header = (
            "<!-- AUTO-REGENERATED by scripts/update-program-changelog.py — PM narrative placeholder is preserved -->\n\n"
            "# Program Changelog\n\n---\n\n"
        )
        changelog_path.write_text(header + new_section)

    print(f"Wrote {changelog_path}")


if __name__ == "__main__":
    main()
